/** @type {import('tailwindcss').Config} */
module.exports = {
  // Tailwind ko batate hain ki kahan se classes scan kare
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      // Material 3 / Lexicon Design System Colors
      colors: {
        "surface-container-highest": "#dce2f3",
        "on-background": "#151c27",
        "on-tertiary": "#ffffff",
        "tertiary": "#7e3000",
        "error-container": "#ffdad6",
        "tertiary-container": "#a44100",
        "secondary-container": "#6063ee",
        "secondary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#ffd2be",
        "inverse-surface": "#2a313d",
        "surface-container-lowest": "#ffffff",
        "outline": "#777587",
        "primary-container": "#4f46e5",
        "surface": "#f9f9ff",
        "primary-fixed-dim": "#c3c0ff",
        "primary": "#3525cd",
        "secondary-fixed": "#e1e0ff",
        "on-primary-fixed": "#0f0069",
        "secondary": "#4648d4",
        "on-surface": "#151c27",
        "error": "#ba1a1a",
        "on-primary-container": "#dad7ff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "inverse-on-surface": "#ebf1ff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-tint": "#4d44e3",
        "inverse-primary": "#c3c0ff",
        "surface-container": "#e7eefe",
        "on-secondary-fixed": "#07006c",
        "on-secondary-container": "#fffbff",
        "primary-fixed": "#e2dfff",
        "surface-variant": "#dce2f3",
        "on-surface-variant": "#464555",
        "on-error-container": "#93000a",
        "surface-container-low": "#f0f3ff",
        "tertiary-fixed-dim": "#ffb695",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-tertiary-fixed": "#351000",
        "on-error": "#ffffff",
        "surface-dim": "#d3daea",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "background": "#f9f9ff",
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "inter": ["Inter", "system-ui", "sans-serif"],
      },
      // Custom spacing from design system
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "24px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
      },
      // Custom font sizes from login.html design
      fontSize: {
        "code": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
